FC=mpifort
FFLAGS=-O3

ex1:
	$(FC) $(FFLAGS) ex1.f90 -o ex1.out
ex2:
	$(FC) $(FFLAGS) ex2.f90 -o ex2.out
ex3:
	$(FC) $(FFLAGS) ex3.f90 -o ex3.out
ex4:
	$(FC) $(FFLAGS) ex4.f90 -o ex4.out
ex5:
	$(FC) $(FFLAGS) ex5.f90 -o ex5.out
clean:
	rm -rf ex1.out
	rm -rf ex2.out
	rm -rf ex3.out
	rm -rf ex4.out
	rm -rf ex5.out
